/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAxelarExecutable } from "./IAxelarExecutable";
export type { IAxelarGasService } from "./IAxelarGasService";
export type { IAxelarGateway } from "./IAxelarGateway";
export type { IContractIdentifier } from "./IContractIdentifier";
export type { IERC20 } from "./IERC20";
export type { IGovernable } from "./IGovernable";
export type { IOwnable } from "./IOwnable";
export type { IProxy } from "./IProxy";
export type { IUpgradable } from "./IUpgradable";
