/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc721DemoSol from "./ERC721demo.sol";
export type { erc721DemoSol };
import type * as nftLinkerSol from "./NFTLinker.sol";
export type { nftLinkerSol };
import type * as proxySol from "./Proxy.sol";
export type { proxySol };
