/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as erc721DemoSol from "./ERC721demo.sol";
export * as nftLinkerSol from "./NFTLinker.sol";
export * as proxySol from "./Proxy.sol";
