/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as callContract from "./call-contract";
export type { callContract };
import type * as callContractWithToken from "./call-contract-with-token";
export type { callContractWithToken };
import type * as nftLinker from "./nft-linker";
export type { nftLinker };
