/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MessageReceiver } from "./MessageReceiver";
export type { MessageSender } from "./MessageSender";
