/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BaseProxy } from "./BaseProxy";
export type { Proxy } from "./Proxy";
export type { Upgradable } from "./Upgradable";
